branches:
  only: 
    - master
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: 
        - cd src && npm run ci.tslint
        - cd ../demo && npm run ci.tslint
        - cd ../demo-angular && npm run ci.tslint
    - stage: "WebPack, Build and Test"
      os: osx
      env:
        - WebpackiOS="11"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd demo && npm run ci.ios.webpack.build
        - cd ../demo-angular && npm run ci.ios.webpack.build
    - language: android
      os: linux
      env:
        - WebpackAndroid="27"
      jdk: oraclejdk8
      before_install: nvm install 8
      script:
        - cd demo && npm run ci.android.webpack.build
        - cd ../demo-angular && npm run ci.android.webpack.build
    - language: android
      env: 
        - BuildAndroid="27"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      script:
        - cd demo && npm run ci.android.build
        - cd ../demo-angular && npm run ci.android.build
    - os: osx
      env: 
        - BuildiOS="11"
        - Xcode="10.0"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd demo && npm run ci.ios.build
        - cd ../demo-angular && npm run ci.ios.build

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - build-tools-27.0.3
    - android-23
    - android-26
    - android-27
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    
